version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-management-app
    ports:
      - "${SERVER_PORT:-9000}:${SERVER_PORT:-9000}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - hotel-network
    restart: always

  db:
    image: mysql:8.0
    container_name: hotel-management-db
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=hotel_management
      - MYSQL_USER=${SPRING_DATASOURCE_USERNAME:-hotel_management}
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-T258ChaZ7M2Q6sBe}
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hotel-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

networks:
  hotel-network:
    driver: bridge

volumes:
  mysql-data: 